shiny:
  proxy:
    title: Open Analytics Shiny Proxy
    logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    port: 8080
    authentication: ldap
    # LDAP configuration
    ldap:
      url: ldap://ldap.forumsys.com:389/dc=example,dc=com
      user-dn-pattern: uid={0}
      group-search-base:
      group-search-filter: (uniqueMember={0})
      manager-dn: cn=read-only-admin,dc=example,dc=com
      manager-password: password
    # Docker configuration
    docker:
      cert-path: /home/none
      url: http://localhost:2375
      host: 127.0.0.1
      port-range-start: 20000
  apps:
  - name: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    docker-cmd: ["R", "-e shinyproxy::run_01_hello()"]
    docker-image: openanalytics/shinyproxy-demo
    ldap-groups: [scientists, mathematicians]
  - name: 06_tabsets
    docker-cmd: ["R", "-e shinyproxy::run_06_tabsets()"]
    docker-image: openanalytics/shinyproxy-demo
    ldap-groups: [scientists]
# useful when debugging; set to 'true' when running in production
spring:
  thymeleaf:
    cache: true
# logging
logging:
  file:
    shinyproxy.log